### ISSUE TITLE
Firebase documents

### ISSUE THREAD

**Issue by vietthang09** [senixus/coffee-shop#3]
Hi, your project very helpful, can i see your firebase documents, thank you!

**Comment by vietthang09** [comment]
I'm learning from your project, I downloaded it and it can't run because firebase is missing, can you show me the structure of firebase store, thanks for the feedback 😍

**Comment by senixus** [comment]
@vietthang09 can you share your email with me, I can send Firebase documents as JSON If it's ok with you.

**Comment by vietthang09** [comment]
vthcvn@gmail.com 
Thanks you.
